#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

#### AUTOSTART ####
sxhkd &
picom &
nitrogen --restore &
#lxappearance &
~/.config/polybar/launch.sh &


bspc monitor -d       

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#### BSPWM coloring ####
bspc config normal_border_color		      "#79740e"
bspc config active_border_color	          "#b8bb26"
bspc config focused_border_color	      "#b8bb26"
bspc config presel_feedback_color	      "#98971a"
bspc config urgent_border_color 	      "#af3a03"



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
